/* The following code was generated by JFlex 1.6.1 */

import java.io.*;
import exceptions.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>../src/oberon.flex</tt>
 */
public class OberonScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\10\1\3\1\2\1\57\1\3\1\1\16\10\4\0\1\3\2\0"+
    "\1\53\1\7\1\0\1\54\1\0\1\4\1\6\1\5\1\55\1\45"+
    "\1\56\1\46\1\0\1\12\7\13\2\11\1\0\1\44\1\51\1\47"+
    "\1\50\2\0\1\21\1\15\1\34\1\27\1\20\1\32\1\25\1\31"+
    "\1\23\2\7\1\17\1\35\1\22\1\16\1\40\1\7\1\26\1\33"+
    "\1\24\1\36\1\41\1\30\1\7\1\37\1\7\1\42\1\0\1\43"+
    "\1\0\1\7\1\0\1\21\1\15\1\34\1\27\1\20\1\32\1\25"+
    "\1\31\1\23\2\7\1\17\1\35\1\22\1\16\1\40\1\7\1\26"+
    "\1\33\1\24\1\36\1\41\1\30\1\7\1\37\1\7\1\0\1\14"+
    "\1\0\1\52\6\10\1\60\32\10\2\0\4\7\4\0\1\7\2\0"+
    "\1\10\7\0\1\7\4\0\1\7\5\0\27\7\1\0\37\7\1\0"+
    "\70\7\2\23\115\7\1\33\u0142\7\4\0\14\7\16\0\5\7\7\0"+
    "\1\7\1\0\1\7\21\0\160\10\5\7\1\0\2\7\2\0\4\7"+
    "\10\0\1\7\1\0\3\7\1\0\1\7\1\0\24\7\1\0\123\7"+
    "\1\0\213\7\1\0\5\10\2\0\236\7\11\0\46\7\2\0\1\7"+
    "\7\0\47\7\7\0\1\7\1\0\55\10\1\0\1\10\1\0\2\10"+
    "\1\0\2\10\1\0\1\10\10\0\33\7\5\0\3\7\15\0\5\10"+
    "\6\0\1\7\4\0\13\10\5\0\53\7\37\10\4\0\2\7\1\10"+
    "\143\7\1\0\1\7\10\10\1\0\6\10\2\7\2\10\1\0\4\10"+
    "\2\7\12\10\3\7\2\0\1\7\17\0\1\10\1\7\1\10\36\7"+
    "\33\10\2\0\131\7\13\10\1\7\16\0\12\10\41\7\11\10\2\7"+
    "\4\0\1\7\5\0\26\7\4\10\1\7\11\10\1\7\3\10\1\7"+
    "\5\10\22\0\31\7\3\10\104\0\1\7\1\0\13\7\67\0\33\10"+
    "\1\0\4\10\66\7\3\10\1\7\22\10\1\7\7\10\12\7\2\10"+
    "\2\0\12\10\1\0\7\7\1\0\7\7\1\0\3\10\1\0\10\7"+
    "\2\0\2\7\2\0\26\7\1\0\7\7\1\0\1\7\3\0\4\7"+
    "\2\0\1\10\1\7\7\10\2\0\2\10\2\0\3\10\1\7\10\0"+
    "\1\10\4\0\2\7\1\0\3\7\2\10\2\0\12\10\4\7\7\0"+
    "\1\7\5\0\3\10\1\0\6\7\4\0\2\7\2\0\26\7\1\0"+
    "\7\7\1\0\2\7\1\0\2\7\1\0\2\7\2\0\1\10\1\0"+
    "\5\10\4\0\2\10\2\0\3\10\3\0\1\10\7\0\4\7\1\0"+
    "\1\7\7\0\14\10\3\7\1\10\13\0\3\10\1\0\11\7\1\0"+
    "\3\7\1\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7\2\0"+
    "\1\10\1\7\10\10\1\0\3\10\1\0\3\10\2\0\1\7\17\0"+
    "\2\7\2\10\2\0\12\10\1\0\1\7\17\0\3\10\1\0\10\7"+
    "\2\0\2\7\2\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7"+
    "\2\0\1\10\1\7\7\10\2\0\2\10\2\0\3\10\10\0\2\10"+
    "\4\0\2\7\1\0\3\7\2\10\2\0\12\10\1\0\1\7\20\0"+
    "\1\10\1\7\1\0\6\7\3\0\3\7\1\0\4\7\3\0\2\7"+
    "\1\0\1\7\1\0\2\7\3\0\2\7\3\0\3\7\3\0\14\7"+
    "\4\0\5\10\3\0\3\10\1\0\4\10\2\0\1\7\6\0\1\10"+
    "\16\0\12\10\11\0\1\7\7\0\3\10\1\0\10\7\1\0\3\7"+
    "\1\0\27\7\1\0\12\7\1\0\5\7\3\0\1\7\7\10\1\0"+
    "\3\10\1\0\4\10\7\0\2\10\1\0\2\7\6\0\2\7\2\10"+
    "\2\0\12\10\22\0\2\10\1\0\10\7\1\0\3\7\1\0\27\7"+
    "\1\0\12\7\1\0\5\7\2\0\1\10\1\7\7\10\1\0\3\10"+
    "\1\0\4\10\7\0\2\10\7\0\1\7\1\0\2\7\2\10\2\0"+
    "\12\10\1\0\2\7\17\0\2\10\1\0\10\7\1\0\3\7\1\0"+
    "\51\7\2\0\1\7\7\10\1\0\3\10\1\0\4\10\1\7\10\0"+
    "\1\10\10\0\2\7\2\10\2\0\12\10\12\0\6\7\2\0\2\10"+
    "\1\0\22\7\3\0\30\7\1\0\11\7\1\0\1\7\2\0\7\7"+
    "\3\0\1\10\4\0\6\10\1\0\1\10\1\0\10\10\22\0\2\10"+
    "\15\0\60\7\1\10\2\7\7\10\4\0\10\7\10\10\1\0\12\10"+
    "\47\0\2\7\1\0\1\7\2\0\2\7\1\0\1\7\2\0\1\7"+
    "\6\0\4\7\1\0\7\7\1\0\3\7\1\0\1\7\1\0\1\7"+
    "\2\0\2\7\1\0\4\7\1\10\2\7\6\10\1\0\2\10\1\7"+
    "\2\0\5\7\1\0\1\7\1\0\6\10\2\0\12\10\2\0\4\7"+
    "\40\0\1\7\27\0\2\10\6\0\12\10\13\0\1\10\1\0\1\10"+
    "\1\0\1\10\4\0\2\10\10\7\1\0\44\7\4\0\24\10\1\0"+
    "\2\10\5\7\13\10\1\0\44\10\11\0\1\10\71\0\53\7\24\10"+
    "\1\7\12\10\6\0\6\7\4\10\4\7\3\10\1\7\3\10\2\7"+
    "\7\10\3\7\4\10\15\7\14\10\1\7\17\10\2\0\46\7\1\0"+
    "\1\7\5\0\1\7\2\0\53\7\1\0\u014d\7\1\0\4\7\2\0"+
    "\7\7\1\0\1\7\1\0\4\7\2\0\51\7\1\0\4\7\2\0"+
    "\41\7\1\0\4\7\2\0\7\7\1\0\1\7\1\0\4\7\2\0"+
    "\17\7\1\0\71\7\1\0\4\7\2\0\103\7\2\0\3\10\40\0"+
    "\20\7\20\0\125\7\14\0\u026c\7\2\0\21\7\1\0\32\7\5\0"+
    "\113\7\3\0\3\7\17\0\15\7\1\0\4\7\3\10\13\0\22\7"+
    "\3\10\13\0\22\7\2\10\14\0\15\7\1\0\3\7\1\0\2\10"+
    "\14\0\64\7\40\10\3\0\1\7\3\0\2\7\1\10\2\0\12\10"+
    "\41\0\3\10\2\0\12\10\6\0\130\7\10\0\51\7\1\10\1\7"+
    "\5\0\106\7\12\0\35\7\3\0\14\10\4\0\14\10\12\0\12\10"+
    "\36\7\2\0\5\7\13\0\54\7\4\0\21\10\7\7\2\10\6\0"+
    "\12\10\46\0\27\7\5\10\4\0\65\7\12\10\1\0\35\10\2\0"+
    "\13\10\6\0\12\10\15\0\1\7\130\0\5\10\57\7\21\10\7\7"+
    "\4\0\12\10\21\0\11\10\14\0\3\10\36\7\15\10\2\7\12\10"+
    "\54\7\16\10\14\0\44\7\24\10\10\0\12\10\3\0\3\7\12\10"+
    "\44\7\122\0\3\10\1\0\25\10\4\7\1\10\4\7\3\10\2\7"+
    "\11\0\300\7\47\10\25\0\4\10\u0116\7\2\0\6\7\2\0\46\7"+
    "\2\0\6\7\2\0\10\7\1\0\1\7\1\0\1\7\1\0\1\7"+
    "\1\0\37\7\2\0\65\7\1\0\7\7\1\0\1\7\3\0\3\7"+
    "\1\0\7\7\3\0\4\7\2\0\6\7\4\0\15\7\5\0\3\7"+
    "\1\0\7\7\16\0\5\10\30\0\1\57\1\57\5\10\20\0\2\7"+
    "\23\0\1\7\13\0\5\10\5\0\6\10\1\0\1\7\15\0\1\7"+
    "\20\0\15\7\3\0\33\7\25\0\15\10\4\0\1\10\3\0\14\10"+
    "\21\0\1\7\4\0\1\7\2\0\12\7\1\0\1\7\3\0\5\7"+
    "\6\0\1\7\1\0\1\7\1\0\1\7\1\0\4\7\1\0\13\7"+
    "\2\0\4\7\5\0\5\7\4\0\1\7\21\0\51\7\u0a77\0\57\7"+
    "\1\0\57\7\1\0\205\7\6\0\4\7\3\10\2\7\14\0\46\7"+
    "\1\0\1\7\5\0\1\7\2\0\70\7\7\0\1\7\17\0\1\10"+
    "\27\7\11\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0"+
    "\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0\40\10\57\0"+
    "\1\7\u01d5\0\3\7\31\0\11\7\6\10\1\0\5\7\2\0\5\7"+
    "\4\0\126\7\2\0\2\10\2\0\3\7\1\0\132\7\1\0\4\7"+
    "\5\0\51\7\3\0\136\7\21\0\33\7\65\0\20\7\u0200\0\u19b6\7"+
    "\112\0\u51cd\7\63\0\u048d\7\103\0\56\7\2\0\u010d\7\3\0\20\7"+
    "\12\10\2\7\24\0\57\7\1\10\4\0\12\10\1\0\31\7\7\0"+
    "\1\10\120\7\2\10\45\0\11\7\2\0\147\7\2\0\4\7\1\0"+
    "\4\7\14\0\13\7\115\0\12\7\1\10\3\7\1\10\4\7\1\10"+
    "\27\7\5\10\20\0\1\7\7\0\64\7\14\0\2\10\62\7\21\10"+
    "\13\0\12\10\6\0\22\10\6\7\3\0\1\7\4\0\12\10\34\7"+
    "\10\10\2\0\27\7\15\10\14\0\35\7\3\0\4\10\57\7\16\10"+
    "\16\0\1\7\12\10\46\0\51\7\16\10\11\0\3\7\1\10\10\7"+
    "\2\10\2\0\12\10\6\0\27\7\3\0\1\7\1\10\4\0\60\7"+
    "\1\10\1\7\3\10\2\7\2\10\5\7\2\10\1\7\1\10\1\7"+
    "\30\0\3\7\2\0\13\7\5\10\2\0\3\7\2\10\12\0\6\7"+
    "\2\0\6\7\2\0\6\7\11\0\7\7\1\0\7\7\221\0\43\7"+
    "\10\10\1\0\2\10\2\0\12\10\6\0\u2ba4\7\14\0\27\7\4\0"+
    "\61\7\u2104\0\u016e\7\2\0\152\7\46\0\7\7\14\0\5\7\5\0"+
    "\1\7\1\10\12\7\1\0\15\7\1\0\5\7\1\0\1\7\1\0"+
    "\2\7\1\0\2\7\1\0\154\7\41\0\u016b\7\22\0\100\7\2\0"+
    "\66\7\50\0\15\7\3\0\20\10\20\0\7\10\14\0\2\7\30\0"+
    "\3\7\31\0\1\7\6\0\5\7\1\0\207\7\2\0\1\10\4\0"+
    "\1\7\13\0\12\10\7\0\32\7\4\0\1\7\1\0\32\7\13\0"+
    "\131\7\3\0\6\7\2\0\6\7\2\0\6\7\2\0\3\7\3\0"+
    "\2\7\3\0\2\7\22\0\3\10\4\0\14\7\1\0\32\7\1\0"+
    "\23\7\1\0\2\7\1\0\17\7\2\0\16\7\42\0\173\7\105\0"+
    "\65\7\210\0\1\10\202\0\35\7\3\0\61\7\57\0\37\7\21\0"+
    "\33\7\65\0\36\7\2\0\44\7\4\0\10\7\1\0\5\7\52\0"+
    "\236\7\2\0\12\10\u0356\0\6\7\2\0\1\7\1\0\54\7\1\0"+
    "\2\7\3\0\1\7\2\0\27\7\252\0\26\7\12\0\32\7\106\0"+
    "\70\7\6\0\2\7\100\0\1\7\3\10\1\0\2\10\5\0\4\10"+
    "\4\7\1\0\3\7\1\0\33\7\4\0\3\10\4\0\1\10\40\0"+
    "\35\7\203\0\66\7\12\0\26\7\12\0\23\7\215\0\111\7\u03b7\0"+
    "\3\10\65\7\17\10\37\0\12\10\20\0\3\10\55\7\13\10\2\0"+
    "\1\10\22\0\31\7\7\0\12\10\6\0\3\10\44\7\16\10\1\0"+
    "\12\10\100\0\3\10\60\7\16\10\4\7\13\0\12\10\u04a6\0\53\7"+
    "\15\10\10\0\12\10\u0936\0\u036f\7\221\0\143\7\u0b9d\0\u042f\7\u33d1\0"+
    "\u0239\7\u04c7\0\105\7\13\0\1\7\56\10\20\0\4\10\15\7\u4060\0"+
    "\2\7\u2163\0\5\10\3\0\26\10\2\0\7\10\36\0\4\10\224\0"+
    "\3\10\u01bb\0\125\7\1\0\107\7\1\0\2\7\2\0\1\7\2\0"+
    "\2\7\2\0\4\7\1\0\14\7\1\0\1\7\1\0\7\7\1\0"+
    "\101\7\1\0\4\7\2\0\10\7\1\0\7\7\1\0\34\7\1\0"+
    "\4\7\1\0\5\7\1\0\1\7\3\0\7\7\1\0\u0154\7\2\0"+
    "\31\7\1\0\31\7\1\0\37\7\1\0\31\7\1\0\37\7\1\0"+
    "\31\7\1\0\37\7\1\0\31\7\1\0\37\7\1\0\31\7\1\0"+
    "\10\7\2\0\62\10\u1600\0\4\7\1\0\33\7\1\0\2\7\1\0"+
    "\1\7\2\0\1\7\1\0\12\7\1\0\4\7\1\0\1\7\1\0"+
    "\1\7\6\0\1\7\4\0\1\7\1\0\1\7\1\0\1\7\1\0"+
    "\3\7\1\0\2\7\1\0\1\7\2\0\1\7\1\0\1\7\1\0"+
    "\1\7\1\0\1\7\1\0\1\7\1\0\2\7\1\0\1\7\2\0"+
    "\4\7\1\0\7\7\1\0\4\7\1\0\4\7\1\0\1\7\1\0"+
    "\12\7\1\0\21\7\5\0\3\7\1\0\5\7\1\0\21\7\u1144\0"+
    "\ua6d7\7\51\0\u1035\7\13\0\336\7\u3fe2\0\u021e\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\10\36\0\140\10\200\0\360\10\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\2\7"+
    "\16\6\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\4\0\2\25"+
    "\1\26\2\27\2\6\1\30\1\31\4\6\1\32\4\6"+
    "\1\33\10\6\1\34\1\35\1\0\2\27\3\6\1\36"+
    "\7\6\1\37\4\6\1\40\1\6\1\41\1\25\1\42"+
    "\2\6\1\43\3\6\1\44\1\45\1\46\1\47\7\6"+
    "\1\42\1\6\1\50\1\51\1\52\2\6\1\53\1\54"+
    "\1\55\1\56\2\6\1\25\1\0\2\6\1\57\1\6"+
    "\1\60\1\6\1\25\1\61\1\62\1\63\2\6\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\61\0\223\0\304\0\61\0\365"+
    "\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405"+
    "\0\61\0\61\0\61\0\61\0\61\0\61\0\u0436\0\u0467"+
    "\0\61\0\61\0\61\0\61\0\61\0\61\0\u0498\0\304"+
    "\0\u04c9\0\u04fa\0\61\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef"+
    "\0\365\0\365\0\u0620\0\u0651\0\u0682\0\u06b3\0\365\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\365\0\u07a8\0\u07d9\0\u080a\0\u083b"+
    "\0\u086c\0\u089d\0\u08ce\0\u08ff\0\61\0\61\0\u0930\0\u0961"+
    "\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\365\0\u0a56\0\u0a87\0\u0ab8"+
    "\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\365\0\u0bad\0\u0bde\0\u0c0f"+
    "\0\u0c40\0\u0c71\0\u0ca2\0\365\0\u0cd3\0\u0d04\0\u0d35\0\u0d66"+
    "\0\365\0\u0d97\0\u0dc8\0\u0df9\0\365\0\365\0\365\0\365"+
    "\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81"+
    "\0\u0fb2\0\365\0\365\0\365\0\u0fe3\0\u1014\0\u1045\0\365"+
    "\0\365\0\365\0\u1076\0\u10a7\0\u0f81\0\u10d8\0\u1109\0\u113a"+
    "\0\365\0\u116b\0\365\0\u119c\0\u11cd\0\365\0\365\0\365"+
    "\0\u11fe\0\u122f\0\365";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\11\1\2\1\13\1\14\1\10\1\15"+
    "\1\16\1\10\1\17\1\20\1\10\1\21\1\22\1\23"+
    "\1\10\1\24\1\10\1\25\1\26\2\10\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\6\46\1\47\1\50"+
    "\55\46\1\4\1\46\1\47\1\50\57\46\1\51\1\52"+
    "\57\46\1\47\1\50\1\53\56\46\1\47\1\50\1\46"+
    "\5\10\1\46\25\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\1\54\1\46\3\11\1\46\25\54\23\46\1\47"+
    "\1\50\1\46\1\54\1\46\1\55\2\12\1\56\25\54"+
    "\23\46\1\47\1\50\1\46\5\10\1\46\1\10\1\57"+
    "\1\10\1\60\21\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\11\10\1\61\3\10\1\62\7\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\2\10\1\63\2\10\1\64\17\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\11\10\1\65\13\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\5\10\1\66\7\10\1\67\7\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\11\10\1\70\2\10"+
    "\1\71\5\10\1\72\2\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\3\10\1\73\21\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\1\10"+
    "\1\74\4\10\1\75\16\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\11\10\1\76\2\10\1\77"+
    "\10\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\4\10\1\100\20\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\1\10\1\101\23\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\1\10"+
    "\1\102\23\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\11\10\1\103\13\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\4\10\1\104\20\10"+
    "\16\46\1\10\4\46\1\47\1\50\41\46\1\105\15\46"+
    "\1\47\1\50\41\46\1\106\15\46\1\51\1\0\57\46"+
    "\1\51\1\50\53\46\5\52\1\107\53\52\4\46\1\47"+
    "\1\50\1\46\5\54\1\46\25\54\16\46\1\54\4\46"+
    "\1\47\1\50\1\46\1\54\1\46\1\55\2\110\1\56"+
    "\25\54\23\46\1\47\1\50\3\46\1\56\2\111\1\56"+
    "\50\46\1\47\1\50\1\46\5\10\1\46\1\10\1\112"+
    "\23\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\10\10\1\113\14\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\16\10\1\114\6\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\12\10"+
    "\1\115\12\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\11\10\1\116\13\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\7\10\1\117\15\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\21\10\1\120\3\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\3\10\1\121\21\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\23\10\1\122"+
    "\1\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\4\10\1\123\12\10\1\124\5\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\24\10\1\125"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\6\10\1\126\16\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\6\10\1\127\16\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\2\10\1\130"+
    "\22\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\5\10\1\131\17\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\12\10\1\132\12\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\1\10"+
    "\1\133\23\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\11\10\1\134\13\10\16\46\1\10\5\52"+
    "\1\135\1\136\52\52\4\46\1\47\1\50\1\46\1\54"+
    "\1\46\3\110\1\46\25\54\23\46\1\47\1\50\3\46"+
    "\3\111\51\46\1\47\1\50\1\46\5\10\1\46\2\10"+
    "\1\137\22\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\6\10\1\140\16\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\3\10\1\141\2\10"+
    "\1\142\16\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\4\10\1\143\20\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\3\10\1\144\21\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\3\10\1\145\21\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\5\10\1\146\17\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\3\10\1\147"+
    "\21\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\12\10\1\150\12\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\1\10\1\151\23\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\7\10"+
    "\1\152\15\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\2\10\1\153\22\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\16\10\1\154\6\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\16\10\1\155\6\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\21\10\1\156\3\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\17\10\1\157"+
    "\5\10\16\46\1\10\5\52\1\135\1\160\52\52\61\0"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\3\10\1\161"+
    "\21\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\5\10\1\162\17\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\15\10\1\163\7\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\22\10"+
    "\1\164\2\10\16\46\1\10\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\10\10\1\165\14\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\11\10\1\166\13\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\3\10\1\167\21\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\3\10\1\170\21\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\3\10\1\171"+
    "\21\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\7\10\1\172\15\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\2\10\1\173\22\10\16\46"+
    "\1\10\4\46\1\47\1\50\1\46\5\10\1\46\3\10"+
    "\1\174\21\10\16\46\1\10\5\175\1\176\53\175\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\4\10\1\177\20\10"+
    "\16\46\1\10\4\46\1\47\1\50\1\46\5\10\1\46"+
    "\3\10\1\200\21\10\16\46\1\10\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\12\10\1\201\12\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\2\10\1\202"+
    "\22\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\3\10\1\203\21\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\12\10\1\204\12\10\16\46"+
    "\1\10\5\175\1\205\1\0\52\175\4\46\1\47\1\50"+
    "\1\46\5\10\1\46\5\10\1\206\17\10\16\46\1\10"+
    "\4\46\1\47\1\50\1\46\5\10\1\46\11\10\1\207"+
    "\13\10\16\46\1\10\4\46\1\47\1\50\1\46\5\10"+
    "\1\46\5\10\1\210\17\10\16\46\1\10\4\46\1\47"+
    "\1\50\1\46\5\10\1\46\21\10\1\211\3\10\16\46"+
    "\1\10\5\175\1\205\53\175\4\46\1\47\1\50\1\46"+
    "\5\10\1\46\11\10\1\212\13\10\16\46\1\10\4\46"+
    "\1\47\1\50\1\46\5\10\1\46\3\10\1\213\21\10"+
    "\16\46\1\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4704];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\44\1\4\0\35\1\1\0\26\1\1\11\37\1"+
    "\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  public boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2914) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException, LexicalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   return Lexical.EOF;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [118] { throw new IllegalSymbolException(); }");
            { throw new IllegalSymbolException();
            }
          case 53: break;
          case 2: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [112] { return Lexical.WhiteSpace; }");
            { return Lexical.WhiteSpace;
            }
          case 54: break;
          case 3: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [80] { return Lexical.LPAREN; }");
            { return Lexical.LPAREN;
            }
          case 55: break;
          case 4: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [99] { return Lexical.MULT; }");
            { return Lexical.MULT;
            }
          case 56: break;
          case 5: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [81] { return Lexical.RPAREN; }");
            { return Lexical.RPAREN;
            }
          case 57: break;
          case 6: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [115] { if(yylength() > 24)"+ZZ_NL+"                                        throw new IllegalIdentifierLengthException();"+ZZ_NL+"                                   return Lexical.Identifier; }");
            { if(yylength() > 24)
                                        throw new IllegalIdentifierLengthException();
                                   return Lexical.Identifier;
            }
          case 58: break;
          case 7: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [101] { if(yylength() > 12)"+ZZ_NL+"                                        throw new IllegalIntegerRangeException();"+ZZ_NL+"                                   return Lexical.Integer; }");
            { if(yylength() > 12)
                                        throw new IllegalIntegerRangeException();
                                   return Lexical.Integer;
            }
          case 59: break;
          case 8: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [82] { return Lexical.LBRACK; }");
            { return Lexical.LBRACK;
            }
          case 60: break;
          case 9: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [83] { return Lexical.RBRACK; }");
            { return Lexical.RBRACK;
            }
          case 61: break;
          case 10: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [84] { return Lexical.SEMICOLON; }");
            { return Lexical.SEMICOLON;
            }
          case 62: break;
          case 11: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [85] { return Lexical.COMMA; }");
            { return Lexical.COMMA;
            }
          case 63: break;
          case 12: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [86] { return Lexical.DOT; }");
            { return Lexical.DOT;
            }
          case 64: break;
          case 13: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [89] { return Lexical.EQ; }");
            { return Lexical.EQ;
            }
          case 65: break;
          case 14: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [90] { return Lexical.GT; }");
            { return Lexical.GT;
            }
          case 66: break;
          case 15: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [91] { return Lexical.LT; }");
            { return Lexical.LT;
            }
          case 67: break;
          case 16: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [92] { return Lexical.NOT; }");
            { return Lexical.NOT;
            }
          case 68: break;
          case 17: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [95] { return Lexical.NOTEQ; }");
            { return Lexical.NOTEQ;
            }
          case 69: break;
          case 18: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [96] { return Lexical.AND; }");
            { return Lexical.AND;
            }
          case 70: break;
          case 19: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [97] { return Lexical.PLUS; }");
            { return Lexical.PLUS;
            }
          case 71: break;
          case 20: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [98] { return Lexical.MINUS; }");
            { return Lexical.MINUS;
            }
          case 72: break;
          case 21: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [109] { throw new MismatchedCommentException(); }");
            { throw new MismatchedCommentException();
            }
          case 73: break;
          case 22: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [104] { throw new IllegalIntegerException(); }");
            { throw new IllegalIntegerException();
            }
          case 74: break;
          case 23: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [105] { throw new IllegalOctalException(); }");
            { throw new IllegalOctalException();
            }
          case 75: break;
          case 24: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [70] { return Lexical.OR; }");
            { return Lexical.OR;
            }
          case 76: break;
          case 25: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [66] { return Lexical.OF; }");
            { return Lexical.OF;
            }
          case 77: break;
          case 26: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [52] { return Lexical.IF; }");
            { return Lexical.IF;
            }
          case 78: break;
          case 27: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [50] { return Lexical.DO; }");
            { return Lexical.DO;
            }
          case 79: break;
          case 28: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [94] { return Lexical.GTEQ; }");
            { return Lexical.GTEQ;
            }
          case 80: break;
          case 29: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [93] { return Lexical.LTEQ; }");
            { return Lexical.LTEQ;
            }
          case 81: break;
          case 30: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [58] { return Lexical.END; }");
            { return Lexical.END;
            }
          case 82: break;
          case 31: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [68] { return Lexical.DIV; }");
            { return Lexical.DIV;
            }
          case 83: break;
          case 32: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [69] { return Lexical.MOD; }");
            { return Lexical.MOD;
            }
          case 84: break;
          case 33: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [67] { return Lexical.VAR; }");
            { return Lexical.VAR;
            }
          case 85: break;
          case 34: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [108] { return Lexical.Comment; }");
            { return Lexical.Comment;
            }
          case 86: break;
          case 35: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [53] { return Lexical.ELSE; }");
            { return Lexical.ELSE;
            }
          case 87: break;
          case 36: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [76] { return Lexical.TRUE; }");
            { return Lexical.TRUE;
            }
          case 88: break;
          case 37: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [55] { return Lexical.THEN; }");
            { return Lexical.THEN;
            }
          case 89: break;
          case 38: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [62] { return Lexical.TYPE; }");
            { return Lexical.TYPE;
            }
          case 90: break;
          case 39: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [71] { return Lexical.READ; }");
            { return Lexical.READ;
            }
          case 91: break;
          case 40: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [57] { return Lexical.BEGIN; }");
            { return Lexical.BEGIN;
            }
          case 92: break;
          case 41: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [54] { return Lexical.ELSIF; }");
            { return Lexical.ELSIF;
            }
          case 93: break;
          case 42: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [65] { return Lexical.ARRAY; }");
            { return Lexical.ARRAY;
            }
          case 94: break;
          case 43: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [72] { return Lexical.WRITE; }");
            { return Lexical.WRITE;
            }
          case 95: break;
          case 44: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [51] { return Lexical.WHILE; }");
            { return Lexical.WHILE;
            }
          case 96: break;
          case 45: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [77] { return Lexical.FALSE; }");
            { return Lexical.FALSE;
            }
          case 97: break;
          case 46: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [56] { return Lexical.CONST; }");
            { return Lexical.CONST;
            }
          case 98: break;
          case 47: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [64] { return Lexical.RECORD; }");
            { return Lexical.RECORD;
            }
          case 99: break;
          case 48: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [61] { return Lexical.MODULE; }");
            { return Lexical.MODULE;
            }
          case 100: break;
          case 49: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [48] { return Lexical.BOOLEAN; }");
            { return Lexical.BOOLEAN;
            }
          case 101: break;
          case 50: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [49] { return Lexical.INTEGER; }");
            { return Lexical.INTEGER;
            }
          case 102: break;
          case 51: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [73] { return Lexical.WRITELN; }");
            { return Lexical.WRITELN;
            }
          case 103: break;
          case 52: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [63] { return Lexical.PROCEDURE; }");
            { return Lexical.PROCEDURE;
            }
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java OberonScanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        OberonScanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new OberonScanner(reader);
          do {
            System.out.println(scanner.yylex());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
