
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 07 18:18:23 CST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LBRACKET = 42;
  public static final int CONST = 25;
  public static final int GE = 13;
  public static final int PERIOD = 41;
  public static final int ELSIF = 31;
  public static final int INTEGER = 17;
  public static final int LPAREN = 44;
  public static final int SEMI = 38;
  public static final int ARRAY = 23;
  public static final int MINUS = 3;
  public static final int WRITE = 20;
  public static final int RPAREN = 45;
  public static final int NOT = 16;
  public static final int AND = 15;
  public static final int LT = 10;
  public static final int RECORD = 22;
  public static final int TYPE = 26;
  public static final int OR = 14;
  public static final int COMMA = 40;
  public static final int BEGIN = 35;
  public static final int PLUS = 2;
  public static final int ASSIGN = 7;
  public static final int IF = 29;
  public static final int WRITELN = 21;
  public static final int LE = 11;
  public static final int OF = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RBRACKET = 43;
  public static final int error = 1;
  public static final int NUMBER = 47;
  public static final int MOD = 6;
  public static final int NEQ = 9;
  public static final int EQ = 8;
  public static final int MODULE = 24;
  public static final int TIMES = 4;
  public static final int COLON = 39;
  public static final int ELSE = 32;
  public static final int READ = 19;
  public static final int WHILE = 33;
  public static final int THEN = 30;
  public static final int END = 36;
  public static final int GT = 12;
  public static final int VAR = 27;
  public static final int PROCEDURE = 28;
  public static final int DO = 34;
  public static final int IDENTIFIER = 46;

  /* non terminals */
  static final int procedure_begin = 5;
  static final int const_list = 11;
  static final int const_declare = 8;
  static final int field_list = 17;
  static final int selector = 29;
  static final int type_declare = 9;
  static final int type_id = 28;
  static final int procedure_body = 7;
  static final int array_type = 31;
  static final int if_statement = 21;
  static final int assignment = 25;
  static final int actual_parameters = 36;
  static final int ap_list = 35;
  static final int field_one = 16;
  static final int expression = 27;
  static final int elsif_statement = 22;
  static final int statement = 19;
  static final int record_type = 32;
  static final int program_code = 0;
  static final int rw_statement = 15;
  static final int procedure_heading = 6;
  static final int else_statement = 23;
  static final int array_part = 14;
  static final int procedure_declaration = 4;
  static final int fp_section = 37;
  static final int type_list = 12;
  static final int var_list = 13;
  static final int while_statement = 20;
  static final int module_block = 1;
  static final int procedure_call = 24;
  static final int var_declare = 10;
  static final int var_if = 26;
  static final int module_begin = 2;
  static final int formal_parameters = 34;
  static final int identifier_list = 30;
  static final int declarations = 3;
  static final int type_but_array = 33;
  static final int statement_sequence = 18;
}

